services:
  signal_generator:
    build:
      context: ./backend/python
      dockerfile: Dockerfile
    container_name: signal_generator
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - SERVICE_NAME=signal_generator
    command: uvicorn api.signal_generator.main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./backend/python:/app

  trade_manager:
    build:
      context: ./backend/python
      dockerfile: Dockerfile
    container_name: trade_manager
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - SERVICE_NAME=trade_manager
    command: uvicorn api.trade_manager.main:app --host 0.0.0.0 --port 8002
    volumes:
      - ./backend/python:/app

  frontend_node:
    build:
      context: ./frontend/server
      dockerfile: Dockerfile
    container_name: frontend_node
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - SIGNAL_GENERATOR_URL=http://signal_generator:8001
      - TRADE_MANAGER_URL=http://trade_manager:8002
    working_dir: /app
    volumes:
      - ./frontend/server:/app
      - /app/node_modules
    command: node index.js
    depends_on:
      - signal_generator
      - trade_manager

  frontend_client:
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
    container_name: frontend_client
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./frontend/client:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - frontend_node